### ISSUE TITLE
Edit create post form for Products section

### ISSUE THREAD

**Issue by sov3333** [sov3333/ga-mern-project#83]
Products are created/updated when user create post (setup)
was thinking something like sketch below, where the products is optional and multi-field:

- 3 text fields for type brand and model.
- hard code a placeholder image for now

![image](https://user-images.githubusercontent.com/8282076/227969521-dbbf0ed3-993a-4e06-b43c-5548559b5579.png)
![image](https://user-images.githubusercontent.com/8282076/227969567-c58c24ec-71e9-4352-b194-0b3b1367fb0a.png)

**Comment by weilianglee87** [comment]
Done !

**Comment by sov3333** [comment]
@weilianglee87 when user creating post should be able to add multiple products e.g. keyboard, mouse, desk

**Comment by sov3333** [comment]
completed with #109  great work everyone!!! @dee-adibah @weilianglee87
