### ISSUE TITLE
Fix featured desk setups section on homepage 

### ISSUE THREAD

**Issue by sov3333** [sov3333/ga-mern-project#96]
- show image, title, username of cards from database
- eye icon link to individual setup page

**Comment by dee-adibah** [comment]
- show image, title, username of cards from database ->DONE
- eye icon link to individual setup page -> having below error tbc tmr

```
SetupOne.jsx:7 Uncaught TypeError: Cannot destructure property 'img' of 'location.state' as it is null.
    at SetupOne (SetupOne.jsx:7:10)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
```

**Comment by sov3333** [comment]
> * show image, title, username of cards from database ->DONE (#PR118)

nice!
also gotta limit to show 5 cards only
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/8282076/228625306-0a12926f-ca60-4b8e-8b46-bc9938900dbd.png">

**Comment by sov3333** [comment]
This one is because the individual setup page is not able to get the props correctly (it currently only works correctly if go from /setups page currently).

In `SetupOne.jsx` page, the props trying to get from location.state. This is passed down from `CardSetup.jsx`.

check line 25-34 in `CardSetup.jsx` component for example how to pass the Link state:
<img width="329" alt="image" src="https://user-images.githubusercontent.com/8282076/228626720-1db8a97d-ff5c-41b9-b4c2-c0847aac8fa6.png">

i think, if u copy the same `state={{ ... }}` to your code it will work. @dee-adibah 


> * eye icon link to individual setup page -> having below error tbc tmr
> 
> ```
> SetupOne.jsx:7 Uncaught TypeError: Cannot destructure property 'img' of 'location.state' as it is null.
>     at SetupOne (SetupOne.jsx:7:10)
>     at renderWithHooks (react-dom.development.js:16305:18)
>     at mountIndeterminateComponent (react-dom.development.js:20074:13)
>     at beginWork (react-dom.development.js:21587:16)
>     at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
>     at invokeGuardedCallback (react-dom.development.js:4277:31)
>     at beginWork$1 (react-dom.development.js:27451:7)
>     at performUnitOfWork (react-dom.development.js:26557:12)
>     at workLoopSync (react-dom.development.js:26466:5)
> ```

**Comment by dee-adibah** [comment]
ok completed and displayed first 5..
but ideally should display those with top 5 likes right?

**Comment by sov3333** [comment]
> ok completed and displayed first 5..
> but ideally should display those with top 5 likes right?

Yea, doubt we have time tho, so let's add the data via seed to show for Saturday

**Comment by sov3333** [comment]
@dee-adibah can u make the 2nd card by open by default? there should be the logic in the original code

![image](https://user-images.githubusercontent.com/8282076/229021166-ddbfdc3d-bfa3-41e3-9ddd-f980d274bdbc.png)

**Comment by sov3333** [comment]
> @dee-adibah can u make the 2nd card by open by default? there should be the logic in the original code
> 

Added @ #137 for stretch goals
